### ISSUE TITLE
Readme erstellen/ausbauen

### ISSUE THREAD

**Issue by florian-huber** [Julimaeder/Write-o-mat#14]

**Comment by BergmannJustin** [comment]
Das README ist fertig geschrieben.
Wir haben dort ein Inhaltsverzeichnis erstellt mit den Themen:
-Vorraussetzungen
-Installation/Anwendung
-Anwendungsbeispiele
-Metadaten

und haben diese abgearbeitet.
Und außerdem wurden noch 2Sticker hinzugefügt.
